### ISSUE TITLE
More info needed!

### ISSUE THREAD

**Issue by acv14003** [tableau/extension-hierarchy-navigator-sandboxed#1]
Hi! I think this would be super useful for a project at work. However, I am having trouble relating the heirachy navigator to any other sheet besides the source.

Any help/more detail would be appreciated!

**Comment by tagyoureit** [comment]
Hi,
were you able to download the sample workbook outlined in the [Readme](https://github.com/tableau/extension-hierarchy-navigator-sandboxed#download-the-manifest-file-and-workbook-with-examples-and-directions-and-a-20182-workbook-with-a-flatdimensional-hierarchy-that-also-shows-dynamic-drill-down)?  The extension can be tied to other sheets via actions, filters and parameters.  The workbook has examples of each.
